# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/keyhan/Softwares-Data/clion-2019.2.5/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/keyhan/Softwares-Data/clion-2019.2.5/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/keyhan/projects/c++/EogenVirtualMachine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/keyhan/projects/c++/EogenVirtualMachine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/keyhan/Softwares-Data/clion-2019.2.5/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/keyhan/Softwares-Data/clion-2019.2.5/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keyhan/projects/c++/EogenVirtualMachine/CMakeFiles /home/keyhan/projects/c++/EogenVirtualMachine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keyhan/projects/c++/EogenVirtualMachine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EogenVirtualMachine

# Build rule for target.
EogenVirtualMachine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EogenVirtualMachine
.PHONY : EogenVirtualMachine

# fast build rule for target.
EogenVirtualMachine/fast:
	$(MAKE) -f CMakeFiles/EogenVirtualMachine.dir/build.make CMakeFiles/EogenVirtualMachine.dir/build
.PHONY : EogenVirtualMachine/fast

v3/Dictionary.o: v3/Dictionary.c.o

.PHONY : v3/Dictionary.o

# target to build an object file
v3/Dictionary.c.o:
	$(MAKE) -f CMakeFiles/EogenVirtualMachine.dir/build.make CMakeFiles/EogenVirtualMachine.dir/v3/Dictionary.c.o
.PHONY : v3/Dictionary.c.o

v3/Dictionary.i: v3/Dictionary.c.i

.PHONY : v3/Dictionary.i

# target to preprocess a source file
v3/Dictionary.c.i:
	$(MAKE) -f CMakeFiles/EogenVirtualMachine.dir/build.make CMakeFiles/EogenVirtualMachine.dir/v3/Dictionary.c.i
.PHONY : v3/Dictionary.c.i

v3/Dictionary.s: v3/Dictionary.c.s

.PHONY : v3/Dictionary.s

# target to generate assembly for a file
v3/Dictionary.c.s:
	$(MAKE) -f CMakeFiles/EogenVirtualMachine.dir/build.make CMakeFiles/EogenVirtualMachine.dir/v3/Dictionary.c.s
.PHONY : v3/Dictionary.c.s

v3/main.o: v3/main.c.o

.PHONY : v3/main.o

# target to build an object file
v3/main.c.o:
	$(MAKE) -f CMakeFiles/EogenVirtualMachine.dir/build.make CMakeFiles/EogenVirtualMachine.dir/v3/main.c.o
.PHONY : v3/main.c.o

v3/main.i: v3/main.c.i

.PHONY : v3/main.i

# target to preprocess a source file
v3/main.c.i:
	$(MAKE) -f CMakeFiles/EogenVirtualMachine.dir/build.make CMakeFiles/EogenVirtualMachine.dir/v3/main.c.i
.PHONY : v3/main.c.i

v3/main.s: v3/main.c.s

.PHONY : v3/main.s

# target to generate assembly for a file
v3/main.c.s:
	$(MAKE) -f CMakeFiles/EogenVirtualMachine.dir/build.make CMakeFiles/EogenVirtualMachine.dir/v3/main.c.s
.PHONY : v3/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... EogenVirtualMachine"
	@echo "... edit_cache"
	@echo "... v3/Dictionary.o"
	@echo "... v3/Dictionary.i"
	@echo "... v3/Dictionary.s"
	@echo "... v3/main.o"
	@echo "... v3/main.i"
	@echo "... v3/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

